Make the NoClassDefFoundError aware of Java3D
When the missing dependency is a Java3D class, we can suggest to call
the 3D Viewer to install Java3D. So we do that now.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>