Add an integration test for our NoSuchMethodError handling
We try to be helpful in identifying situations where contradicting
.jar file versions are in the class path. Since this is such a useful
tool in particular with Bio-Formats, let's let Maven make really sure
that this continues to work as expected.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>