Handle NoSuchMethodErrors in plugins
There are two ways to call plugins in ImageJ 1.x: the regular mechanism
calls IJ.run() -- which we intercept to support the Fiji's Command
infrastructure that was not accepted upstream but that is used by
some Fiji components -- and IJ.runUserPlugIn() -- which is called
e.g. by HandleExtraFileTypes.

This commit adds intercepts for NoSuchMethodError, looking closely
whether there are class path problems.

The idea came to this developer while looking at the n'th loci_tools.jar
issue: http://fiji.sc/bugzilla/show_bug.cgi?id=542

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>